name: Publish

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - test-v*

jobs:
  Build:
    name: Build Package
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: otel-linux-arm64
            target: arm64-unknown-linux-gnu
            arch: arm64
        
    runs-on: ${{ matrix.settings.host }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.9"
      - name: Setup env
        if: ${{ matrix.settings.setup }}
        shell: bash
        run: ${{ matrix.settings.setup }}
      - name: Install
        run: npm install --arch=${{ matrix.settings.arch }}
      - name: Gyp rebuild
        run: node ./scripts/rebuild.js && npx node-gyp rebuild --arch=${{ matrix.settings.arch }}
        env:
          NODE_ARCH: ${{ matrix.settings.arch }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bindings-${{ matrix.settings.target }}
          path: |
            ./build/Release/*.node
            ./build/Release/*.dll
          if-no-files-found: error
