name: Publish

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - v*

jobs:
  Build:
    name: Build Package
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - host: windows-2022
            target: x86_64-pc-windows-msvc
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
            setup: |
              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*;
              export CC=$(xcrun -f clang);
              export CXX=$(xcrun -f clang++);
              SYSROOT=$(xcrun --sdk macosx --show-sdk-path);
              export CFLAGS="-isysroot $SYSROOT -isystem $SYSROOT";
            arch: arm64
          - host: ubuntu-22.04
            target: aarch64-unknown-linux-gnu
            setup: |
              sudo apt-get update
              sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
              export CC=aarch64-linux-gnu-gcc
              export CXX=aarch64-linux-gnu-g++
              export AR=aarch64-linux-gnu-ar
              export AS=aarch64-linux-gnu-as
              export LD=aarch64-linux-gnu-ld
              export STRIP=aarch64-linux-gnu-strip
              sudo cp /usr/bin/aarch64-linux-gnu-gcc /usr/bin/gcc
              sudo cp /usr/bin/aarch64-linux-gnu-g++ /usr/bin/g++
              sudo cp /usr/bin/aarch64-linux-gnu-ar /usr/bin/ar
              sudo cp /usr/bin/aarch64-linux-gnu-as /usr/bin/as
              sudo cp /usr/bin/aarch64-linux-gnu-ld /usr/bin/ld
              sudo cp /usr/bin/aarch64-linux-gnu-strip /usr/bin/strip
            arch: arm64

    runs-on: ${{ matrix.settings.host }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.9"
      - name: Force node-gyp to VS2022 on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          npm config set msvs_version 2022
          echo "GYP_MSVS_VERSION=2022" >> $env:GITHUB_ENV
      - name: Setup env
        if: ${{ matrix.settings.setup }}
        shell: bash
        run: ${{ matrix.settings.setup }}
      - name: Install
        run: npm install --arch=${{ matrix.settings.arch }}
      - name: Gyp rebuild
        run: node ./scripts/rebuild.js --arch=${{ matrix.settings.arch }} && npx node-gyp rebuild --arch=${{ matrix.settings.arch }}